import { defineConfig, globalIgnores } from 'eslint/config'

import { architectureConfig } from './eslint/architecture.js'

export default defineConfig([
  globalIgnores([
    'dist',
    'coverage',
    // FR-TOOL-005: generated by @tanstack/router-plugin, never edited.
    'src/routeTree.gen.ts',
    // Deliberate violations — linted by tests/lint/boundaries.test.ts instead.
    'tests/domains/_lint-check',
  ]),
  ...architectureConfig(),
])
