export const KNOWLEDGE_COPY = {
  browser: {
    empty: 'No knowledge-base documents match the current filters.',
    loadError: 'Knowledge-base documents could not be loaded.',
  },
  filters: {
    source: 'Source',
    topic: 'Topic',
    tags: 'Tags',
    from: 'Published from',
    to: 'Published to',
    flagged: 'Flagged for removal',
  },
  table: {
    caption: 'Knowledge-base documents',
    title: 'Title',
    source: 'Source',
    topic: 'Topic',
    tags: 'Tags',
    credibility: 'Credibility',
    status: 'Status',
    flagged: 'Flagged',
    notFlagged: 'Not flagged',
    notAvailable: 'Not available',
    untitled: 'Untitled document',
    moreTags: (count: number) => `+${count}`,
  },
  credibility: {
    high: 'High credibility',
    review: 'Needs review',
    low: 'Low credibility',
  },
  editor: {
    title: 'Title',
    topic: 'Topic',
    tags: 'Tags',
    content: 'Content',
    datePublished: 'Published',
    metadata: 'Metadata (JSON)',
    metadataInvalid: 'Metadata must be a valid JSON object.',
    save: 'Save',
    saving: 'Saving…',
    saveSuccess: 'Document saved.',
    saveFailure: 'The document could not be saved.',
    conflict: 'This document changed since it was opened.',
    validation: (detail: string) => `Could not save: ${detail}`,
    noChanges: 'No changes to save.',
    reembedWarningTitle: 'This will re-embed the document',
    reembedWarningMessage:
      'Changing the content triggers a live re-embed, which changes retrieval for every user immediately.',
    reembedWarningConfirm: 'Save and re-embed',
    resetCredibilitySuccess: 'Credibility score restored.',
    resetCredibilityFailure: 'The credibility score could not be restored.',
    restoreScore: 'Restore score',
    rollbackConfirmTitle: 'Roll back this document?',
    rollbackConfirmMessage: 'This reverts the document to its prior synthesized state.',
    rollbackConfirmLabel: 'Roll back',
    rollbackSuccess: 'Document rolled back.',
    rollbackFailure: 'The document could not be rolled back.',
    rollback: 'Roll back',
    deleteConfirmTitle: 'Delete this document?',
    deleteConfirmMessage: 'This permanently removes the document from the knowledge base.',
    deleteConfirmLabel: 'Delete',
    deleteSuccess: 'Document deleted.',
    deleteFailure: 'The document could not be deleted.',
    delete: 'Delete',
    discardTitle: 'Discard unsaved changes?',
    discardMessage: 'You have unsaved edits to this document. Leaving now will discard them.',
    discardConfirmLabel: 'Discard changes',
  },
  drawer: {
    title: 'Knowledge document',
    loading: 'Loading document…',
    loadError: 'The document could not be loaded.',
  },
  // KB source ingestion view (admin-api.md "KB Source Ingestion"); the legacy dashboard's wording
  // is preserved where it was already specific.
  sources: {
    list: {
      title: 'Ingested sources',
      caption: 'Ingested KB sources',
      source: 'Source',
      documents: 'Documents',
      actions: 'Actions',
      empty: 'No KB sources ingested yet.',
      loadError: 'Ingested sources could not be loaded.',
      delete: 'Delete',
      deleteLabel: (source: string) => `Delete source ${source}`,
      deleting: 'Deleting…',
      deleteConfirmTitle: 'Delete source?',
      deleteConfirmMessage: (source: string, count: number) =>
        `This will permanently delete all ${count} document(s) ingested under “${source}” and their chunks. This cannot be undone.`,
      deleteConfirmLabel: 'Delete',
      deleteSuccess: (source: string, count: number) => `Deleted ${count} document(s) for “${source}”.`,
      deleteFailure: 'The source could not be deleted.',
    },
    run: {
      title: 'Current run',
      phase: {
        idle: 'Idle',
        running: 'Running',
        completed: 'Completed',
        failed: 'Failed',
      },
      type: {
        web: 'web crawl',
        file: 'file upload',
      },
      heading: (phase: string, name: string | null, type: string | null) =>
        `${phase}${name === null ? '' : `: ${name}`}${type === null ? '' : ` (${type})`}`,
      pagesCrawled: 'Pages crawled',
      processed: 'Processed',
      chunksWritten: 'Chunks written',
      itemErrors: (count: number) => `${count} item error(s) during this run.`,
      statusError: 'The run status could not be refreshed.',
      finished: (chunks: number) => `KB source run finished: ${chunks} chunk(s) written.`,
      finishedWithErrors: (chunks: number, errors: number) =>
        `KB source run finished: ${chunks} chunk(s) written (${errors} item error(s)).`,
      failed: (error: string) => `KB source run failed: ${error}`,
      unknownError: 'unknown error',
      inProgress: 'A KB source run is already in progress — showing its status.',
      noRunId: '—',
    },
    override: {
      title: 'Source already exists',
      message: (name: string) =>
        `A KB source named “${name}” already has documents. Override and replace them with this run?`,
      confirm: 'Override',
    },
    web: {
      title: 'Web crawl',
      name: 'Name',
      urls: 'URLs (one per line, up to 20)',
      topic: 'Topic (optional)',
      maxDepth: 'Max depth',
      maxPages: 'Max pages',
      allowedDomains: 'Allowed domains (comma-separated, optional)',
      allowedDomainsHint: 'Defaults to each URL’s own hostname when left blank.',
      excludePatterns: 'Exclude patterns (comma-separated, optional)',
      ingestLinkedFiles: 'Ingest linked PDF files',
      ingestLinkedFilesHint: 'Download and index PDFs discovered via links on crawled pages, in addition to HTML pages.',
      synthesize: 'Synthesize with AI before indexing',
      synthesizeHint:
        'Runs each page through the KB synthesizer to produce a more concise, RAG-friendly document instead of indexing the raw extracted text. Adds one LLM call per page; falls back to the raw page content if synthesis fails.',
      advanced: 'Advanced: headers / cookies (optional)',
      headers: 'Headers (JSON object, optional)',
      headersPlaceholder: '{"Authorization": "Bearer ..."}',
      cookies: 'Cookies (JSON object, optional)',
      cookiesPlaceholder: '{"session_id": "..."}',
      advancedHint: 'Sent as-is for this run only — not persisted or shown in run status or audit logs.',
      submit: 'Start web crawl',
      starting: 'Starting…',
      started: (runId: string) => `Web crawl started (run ${runId}).`,
      overrideStarted: (runId: string) => `Override crawl started (run ${runId}).`,
      failure: 'The web crawl could not be started.',
    },
    file: {
      title: 'Upload files',
      name: 'Name',
      topic: 'Topic (optional)',
      files: 'Files',
      filesHint: 'Up to 10 MB per file and 50 MB in total.',
      synthesize: 'Synthesize with AI before indexing',
      synthesizeHint:
        'Runs each file through the KB synthesizer to produce a more concise, RAG-friendly document instead of indexing the raw file text. Adds one LLM call per file; falls back to the raw file content if synthesis fails.',
      submit: 'Upload & ingest',
      uploading: 'Uploading…',
      started: (runId: string) => `File ingestion started (run ${runId}).`,
      overrideStarted: (runId: string) => `Override ingestion started (run ${runId}).`,
      failure: 'The file ingestion could not be started.',
    },
    issues: {
      'name-required': 'Name is required.',
      'urls-required': 'At least one URL is required.',
      'too-many-urls': 'Enter at most 20 URLs.',
      'invalid-depth': 'Max depth must be a whole number of 0 or more.',
      'invalid-pages': 'Max pages must be a whole number between 1 and 10000.',
      'invalid-json': 'Must be valid JSON.',
      'not-a-string-map': 'Must be a JSON object mapping names to string values.',
      'files-required': 'At least one file is required.',
    },
  },
} as const