export const KNOWLEDGE_COPY = {
  browser: {
    empty: 'No knowledge-base documents match the current filters.',
    loadError: 'Knowledge-base documents could not be loaded.',
  },
  filters: {
    source: 'Source',
    topic: 'Topic',
    tags: 'Tags',
    from: 'Published from',
    to: 'Published to',
    flagged: 'Flagged for removal',
  },
  table: {
    caption: 'Knowledge-base documents',
    title: 'Title',
    source: 'Source',
    topic: 'Topic',
    tags: 'Tags',
    credibility: 'Credibility',
    status: 'Status',
    flagged: 'Flagged',
    notFlagged: 'Not flagged',
    notAvailable: 'Not available',
    untitled: 'Untitled document',
    moreTags: (count: number) => `+${count}`,
  },
  credibility: {
    high: 'High credibility',
    review: 'Needs review',
    low: 'Low credibility',
  },
  editor: {
    title: 'Title',
    topic: 'Topic',
    tags: 'Tags',
    content: 'Content',
    datePublished: 'Published',
    metadata: 'Metadata (JSON)',
    metadataInvalid: 'Metadata must be a valid JSON object.',
    save: 'Save',
    saving: 'Saving…',
    saveSuccess: 'Document saved.',
    saveFailure: 'The document could not be saved.',
    conflict: 'This document changed since it was opened.',
    validation: (detail: string) => `Could not save: ${detail}`,
    noChanges: 'No changes to save.',
    reembedWarningTitle: 'This will re-embed the document',
    reembedWarningMessage:
      'Changing the content triggers a live re-embed, which changes retrieval for every user immediately.',
    reembedWarningConfirm: 'Save and re-embed',
    resetCredibilitySuccess: 'Credibility score restored.',
    resetCredibilityFailure: 'The credibility score could not be restored.',
    restoreScore: 'Restore score',
    rollbackConfirmTitle: 'Roll back this document?',
    rollbackConfirmMessage: 'This reverts the document to its prior synthesized state.',
    rollbackConfirmLabel: 'Roll back',
    rollbackSuccess: 'Document rolled back.',
    rollbackFailure: 'The document could not be rolled back.',
    rollback: 'Roll back',
    deleteConfirmTitle: 'Delete this document?',
    deleteConfirmMessage: 'This permanently removes the document from the knowledge base.',
    deleteConfirmLabel: 'Delete',
    deleteSuccess: 'Document deleted.',
    deleteFailure: 'The document could not be deleted.',
    delete: 'Delete',
    discardTitle: 'Discard unsaved changes?',
    discardMessage: 'You have unsaved edits to this document. Leaving now will discard them.',
    discardConfirmLabel: 'Discard changes',
  },
  drawer: {
    title: 'Knowledge document',
    loading: 'Loading document…',
    loadError: 'The document could not be loaded.',
  },
} as const