export const REVIEW_COPY = {
  queue: {
    empty: 'No feedback entries match the current filters.',
    loadError: 'Feedback could not be loaded.',
    retry: 'Retry',
  },
  filters: {
    rating: 'Rating',
    decision: 'Decision',
    tags: 'Tags',
    from: 'From',
    to: 'To',
    all: 'All',
    allWithPending: 'All (includes pending)',
    positive: 'Positive',
    negative: 'Negative',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  table: {
    selectAll: 'Select all rejected entries',
    selectEntry: (query: string) => `Select rejected entry: ${query}`,
    user: 'User',
    rating: 'Rating',
    status: 'Status',
    query: 'Query',
    created: 'Created',
    tags: 'Tags',
    moreTags: (count: number) => `+${count}`,
  },
  bulk: {
    delete: (count: number) => `Delete ${count}`,
    title: (count: number) => (count === 1 ? 'Delete rejected entry?' : `Delete ${count} rejected entries?`),
    message: (count: number) =>
      count === 1
        ? 'Delete this rejected entry? This cannot be undone.'
        : `Delete ${count} rejected entries? This cannot be undone.`,
    confirm: 'Delete',
    success: (count: number) => `Deleted ${count} rejected ${count === 1 ? 'entry' : 'entries'}.`,
    partial: (deleted: number, failed: number) =>
      `Deleted ${deleted} of ${deleted + failed} rejected entries. ${failed} could not be deleted.`,
    failedIds: (ids: readonly string[]) => `Failed: ${ids.join(', ')}`,
  },
  drawer: {
    title: 'Review feedback',
    loading: 'Loading feedback entry',
    loadError: 'Feedback entry could not be loaded.',
    details: 'Details',
    metadata: 'Feedback metadata',
    history: 'Message history',
    content: 'Content',
    previousDecision: 'Previous decision',
    synthesis: 'KB synthesis',
    rolledBack: (by: string | null, reason: string | null) =>
      `Rolled back${by === null ? '' : ` by ${by}`}${reason === null ? '' : `: ${reason}`}`,
    user: 'User',
    model: 'Model',
    created: 'Created',
    sources: 'KB sources',
    correction: 'Correction',
    comment: 'User comment',
  },
  form: {
    title: 'Decision',
    decision: 'Review decision',
    tags: 'Reviewer tags',
    comment: 'Reviewer comment',
    save: 'Save review',
    saving: 'Saving review',
    requiredDecision: 'Please select a decision.',
    conflict: 'Status transition not allowed. Reload entry and try again.',
    validation: (detail: string) => `Validation error: ${detail}`,
    failure: 'Review could not be saved.',
    success: 'Review saved.',
  },
  tags: {
    input: 'Add tag',
    add: 'Add tag',
    remove: (tag: string) => `Remove ${tag}`,
    empty: 'Tag cannot be empty',
    tooLong: 'Tag must be ≤32 characters',
    pattern: 'Tag must match pattern [A-Za-z0-9_-]',
    duplicate: 'Tag is already added',
    maximum: 'Maximum 20 tags allowed',
  },
  // FR-REV-015/015a/015b/015c: synthesis trigger, rollback (with its double confirmation), and
  // the per-status-code copy for the ways either action can fail.
  synthesis: {
    neverHint: 'This entry has not been added to the knowledge base yet.',
    phaseRunningHint: 'A batch synthesis run is in progress. Try again once it finishes.',
    phaseUnknownHint: 'Batch synthesis status is unavailable. Reopen the entry to check again.',
    trigger: 'Synthesize',
    retrigger: 'Re-synthesize',
    rollback: 'Roll back',
    synthesizedStatus: (id: string) => `Synthesized into ${id}`,
    synthesizeSuccess: (id: string | null) => (id === null ? 'Synthesized.' : `Synthesized into ${id}.`),
    synthesizeConflict: 'Already synthesized — reload to refresh.',
    synthesizeValidation: 'Validation error: entry is not eligible for synthesis.',
    rollbackPromptTitle: 'Roll back this article?',
    rollbackPromptMessage: 'Optionally explain why this article is being rolled back.',
    rollbackPromptLabel: 'Reason (optional)',
    rollbackPromptConfirm: 'Roll back',
    rollbackConfirmTitle: 'Roll back this article without a reason?',
    rollbackConfirmMessage: 'No reason was entered. Roll back anyway?',
    rollbackConfirmLabel: 'Roll back',
    rollbackSuccess: (count: number) =>
      `Rolled back. ${count} feedback ${count === 1 ? 'entry' : 'entries'} reverted.`,
    rollbackNotSynthesized: 'This document is not a synthesized article.',
    rollbackServerError: 'Rollback failed — check server logs.',
    genericFailure: 'That could not be completed. Please try again.',
  },
  stats: {
    title: 'Feedback stats',
    loadError: 'Stats could not be loaded.',
    retry: 'Retry',
    total: 'Total',
    pendingReview: 'Pending review',
    approved: 'Approved',
    rejected: 'Rejected',
    positive: 'Positive',
    negative: 'Negative',
    withCorrection: 'With correction',
    integrated: 'Integrated',
    oldestPending: (hours: number) => `Oldest: ${hours}h`,
    topTagsChart: 'Top tags',
    topTagsTable: 'Top tags (table view)',
    topTagsEmpty: 'No tags recorded yet.',
    tagColumn: 'Tag',
    countColumn: 'Count',
  },
  badge: {
    pending: (count: number) => `${count} pending review`,
    pendingCapped: '99+ pending review',
  },
} as const