export const TELEMETRY_COPY = {
  title: 'Token usage',
  summary: {
    title: 'Per-model summary',
    chart: 'Total tokens per model',
    table: 'Token usage by model',
    model: 'Model',
    input: 'Input',
    output: 'Output',
    turns: 'Turns',
    empty: 'No token usage recorded yet.',
    loadError: 'Model token usage could not be loaded.',
    chartTableDescription: 'The table below contains the same model totals in accessible form.',
  },
  topUsers: {
    title: 'Top users',
    limit: 'Users to show',
    user: 'User',
    input: 'Input',
    output: 'Output',
    empty: 'No token usage recorded yet.',
    loadError: 'Top users could not be loaded.',
  },
  byDay: {
    title: 'By day',
    start: 'Start date',
    end: 'End date',
    apply: 'Apply',
    chart: 'Token trend by day',
    table: 'Token usage by day',
    date: 'Date',
    input: 'Input',
    output: 'Output',
    turns: 'Turns',
    beforeApply: 'Select a start and end date, then Apply.',
    empty: 'No token usage recorded in this range.',
    invalidRange: 'End date must be after start date.',
    loadError: 'Daily token usage could not be loaded.',
    chartTableDescription: 'The table below contains the same daily values in accessible form.',
  },
  byUser: {
    title: 'By user',
    user: 'User ID',
    userPlaceholder: 'e.g. alice@example.com',
    apply: 'Apply',
    session: 'Session',
    model: 'Model',
    input: 'Input',
    output: 'Output',
    timestamp: 'Turn timestamp',
    beforeApply: 'Enter a user ID, then Apply.',
    empty: 'No token usage recorded for this user.',
    loadError: 'User token usage could not be loaded.',
  },
  pagination: {
    label: 'User usage pagination',
    empty: 'No results.',
    range: (from: number, to: number) => `Showing ${from}–${to}`,
    previous: 'Previous',
    next: 'Next',
  },
} as const