"""
Conversation metadata storage — abstract interface.

Concrete backends live in:

* :mod:`autolangchat.db.conversation_sqlite` (zero-config default)
* :mod:`autolangchat.db.conversation_postgres` (production)

Use :func:`autolangchat.db.create_conversation_store` to build the backend
selected by ``ChatConfig.conversation_storage_type``.

This store is a lightweight metadata index only (id, user_id, title,
timestamps) mapping user identities to their LangGraph conversation threads.
LangGraph checkpoint data (accessed via ``chat_graph.aget_state``) remains
the single source of truth for message history — there is deliberately no
``messages`` table here.

Row shape
---------
Every method that returns conversation data (``get_conversation``,
``list_conversations``) returns plain ``dict`` rows with the keys:

* ``id`` (str) — the conversation id, equal to the LangGraph ``thread_id``.
* ``user_id`` (str)
* ``title`` (Optional[str])
* ``created_at`` / ``updated_at`` (str, ISO-8601 UTC)
* ``message_count`` (int)
* ``metadata`` (dict)
* ``is_archived`` (bool)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional


class BaseConversationStore(ABC):
    """Abstract async data-access layer for per-user conversation metadata.

    Concrete backends (SQLite, Postgres) implement the same surface so the
    rest of the codebase — notably the WebSocket handler and REST API —
    doesn't depend on the storage technology.
    """

    @abstractmethod
    async def open(self) -> None:
        """Acquire any underlying resources and (optionally) bootstrap schema."""

    @abstractmethod
    async def close(self) -> None:
        """Release underlying resources."""

    @abstractmethod
    async def create_conversation(
        self,
        conversation_id: str,
        user_id: str,
        title: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Register a new conversation.

        ``conversation_id`` must equal the LangGraph checkpoint ``thread_id``
        for this conversation — it is supplied by the caller, never
        generated by the store. If the backend was constructed with a
        ``max_conversations_per_user`` cap, the oldest conversation(s) for
        ``user_id`` beyond the cap are pruned (metadata row only; the
        corresponding LangGraph checkpoint is left for the existing
        checkpoint TTL sweep to clean up).
        """

    @abstractmethod
    async def get_conversation(self, conversation_id: str) -> Optional[Dict[str, Any]]:
        """Return the conversation row for ``conversation_id``, or ``None`` if missing."""

    @abstractmethod
    async def list_conversations(
        self,
        user_id: str,
        limit: int = 50,
        offset: int = 0,
    ) -> List[Dict[str, Any]]:
        """Return ``user_id``'s conversations, newest-updated first.

        ``limit`` must be positive, ``offset`` non-negative.
        """

    @abstractmethod
    async def update_conversation(
        self,
        conversation_id: str,
        title: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Patch ``title`` and/or ``metadata`` on an existing conversation.

        At least one of ``title``/``metadata`` must be provided. Always
        bumps ``updated_at``.

        Raises
        ------
        ConversationNotFoundError
            if no conversation with ``conversation_id`` exists.
        """

    @abstractmethod
    async def record_turn(self, conversation_id: str) -> None:
        """Increment ``message_count`` and bump ``updated_at`` for a turn.

        Raises
        ------
        ConversationNotFoundError
            if no conversation with ``conversation_id`` exists.
        """

    @abstractmethod
    async def delete_conversation(self, conversation_id: str) -> None:
        """Remove the metadata row for ``conversation_id``.

        Idempotent: deleting a conversation that doesn't exist (or was
        already deleted) is not an error. Only the metadata row is
        removed — the LangGraph checkpoint row is cleaned up separately by
        the existing checkpoint TTL sweep.
        """

    @abstractmethod
    async def delete_all_conversations(self, user_id: str) -> int:
        """Remove every conversation metadata row belonging to ``user_id``.

        Returns the number of rows deleted.
        """

    @abstractmethod
    async def get_conversation_count(self, user_id: str) -> int:
        """Return the number of conversations belonging to ``user_id``."""
