"""MCP (Model Context Protocol) server support.

Exposes the same OpenAPI-derived tools generated by ``ToolsGenerator`` /
executed by ``ToolManager`` to MCP clients (Claude Desktop, VS Code Copilot,
etc.) via the Streamable HTTP transport, without going through the
LangGraph/Bedrock chat loop. See :mod:`autolangchat.mcp.server`.

Requires the optional ``mcp`` extra: ``pip install autolangchat[mcp]``.
"""
