/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardKbBrowserRouteImport } from './routes/dashboard/kb-browser'
import { Route as DashboardReviewedRouteImport } from './routes/dashboard/reviewed'
import { Route as DashboardTokenUsagesRouteImport } from './routes/dashboard/token-usages'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as DashboardFeedbackIndexRouteImport } from './routes/dashboard/feedback.index'
import { Route as DashboardFeedbackStatsRouteImport } from './routes/dashboard/feedback.stats'
import { Route as UiCConversationIdRouteImport } from './routes/ui/c.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardKbBrowserRoute = DashboardKbBrowserRouteImport.update({
  id: '/kb-browser',
  path: '/kb-browser',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewedRoute = DashboardReviewedRouteImport.update({
  id: '/reviewed',
  path: '/reviewed',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTokenUsagesRoute = DashboardTokenUsagesRouteImport.update({
  id: '/token-usages',
  path: '/token-usages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFeedbackIndexRoute = DashboardFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFeedbackStatsRoute = DashboardFeedbackStatsRouteImport.update({
  id: '/feedback/stats',
  path: '/feedback/stats',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UiCConversationIdRoute = UiCConversationIdRouteImport.update({
  id: '/ui/c/$conversationId',
  path: '/ui/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/kb-browser': typeof DashboardKbBrowserRoute
  '/dashboard/reviewed': typeof DashboardReviewedRoute
  '/dashboard/token-usages': typeof DashboardTokenUsagesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ui/': typeof UiIndexRoute
  '/dashboard/feedback/stats': typeof DashboardFeedbackStatsRoute
  '/ui/c/$conversationId': typeof UiCConversationIdRoute
  '/dashboard/feedback/': typeof DashboardFeedbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/kb-browser': typeof DashboardKbBrowserRoute
  '/dashboard/reviewed': typeof DashboardReviewedRoute
  '/dashboard/token-usages': typeof DashboardTokenUsagesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ui': typeof UiIndexRoute
  '/dashboard/feedback/stats': typeof DashboardFeedbackStatsRoute
  '/ui/c/$conversationId': typeof UiCConversationIdRoute
  '/dashboard/feedback': typeof DashboardFeedbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/kb-browser': typeof DashboardKbBrowserRoute
  '/dashboard/reviewed': typeof DashboardReviewedRoute
  '/dashboard/token-usages': typeof DashboardTokenUsagesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ui/': typeof UiIndexRoute
  '/dashboard/feedback/stats': typeof DashboardFeedbackStatsRoute
  '/ui/c/$conversationId': typeof UiCConversationIdRoute
  '/dashboard/feedback/': typeof DashboardFeedbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/kb-browser'
    | '/dashboard/reviewed'
    | '/dashboard/token-usages'
    | '/dashboard/'
    | '/ui/'
    | '/dashboard/feedback/stats'
    | '/ui/c/$conversationId'
    | '/dashboard/feedback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/kb-browser'
    | '/dashboard/reviewed'
    | '/dashboard/token-usages'
    | '/dashboard'
    | '/ui'
    | '/dashboard/feedback/stats'
    | '/ui/c/$conversationId'
    | '/dashboard/feedback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/kb-browser'
    | '/dashboard/reviewed'
    | '/dashboard/token-usages'
    | '/dashboard/'
    | '/ui/'
    | '/dashboard/feedback/stats'
    | '/ui/c/$conversationId'
    | '/dashboard/feedback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  UiIndexRoute: typeof UiIndexRoute
  UiCConversationIdRoute: typeof UiCConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/kb-browser': {
      id: '/dashboard/kb-browser'
      path: '/kb-browser'
      fullPath: '/dashboard/kb-browser'
      preLoaderRoute: typeof DashboardKbBrowserRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviewed': {
      id: '/dashboard/reviewed'
      path: '/reviewed'
      fullPath: '/dashboard/reviewed'
      preLoaderRoute: typeof DashboardReviewedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/token-usages': {
      id: '/dashboard/token-usages'
      path: '/token-usages'
      fullPath: '/dashboard/token-usages'
      preLoaderRoute: typeof DashboardTokenUsagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/feedback/': {
      id: '/dashboard/feedback/'
      path: '/feedback'
      fullPath: '/dashboard/feedback/'
      preLoaderRoute: typeof DashboardFeedbackIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/feedback/stats': {
      id: '/dashboard/feedback/stats'
      path: '/feedback/stats'
      fullPath: '/dashboard/feedback/stats'
      preLoaderRoute: typeof DashboardFeedbackStatsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/ui/c/$conversationId': {
      id: '/ui/c/$conversationId'
      path: '/ui/c/$conversationId'
      fullPath: '/ui/c/$conversationId'
      preLoaderRoute: typeof UiCConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardKbBrowserRoute: typeof DashboardKbBrowserRoute
  DashboardReviewedRoute: typeof DashboardReviewedRoute
  DashboardTokenUsagesRoute: typeof DashboardTokenUsagesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFeedbackStatsRoute: typeof DashboardFeedbackStatsRoute
  DashboardFeedbackIndexRoute: typeof DashboardFeedbackIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardKbBrowserRoute: DashboardKbBrowserRoute,
  DashboardReviewedRoute: DashboardReviewedRoute,
  DashboardTokenUsagesRoute: DashboardTokenUsagesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFeedbackStatsRoute: DashboardFeedbackStatsRoute,
  DashboardFeedbackIndexRoute: DashboardFeedbackIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  UiIndexRoute: UiIndexRoute,
  UiCConversationIdRoute: UiCConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
